env:
  es6: true
  node: true
extends: 'eslint:all'
parserOptions:
  ecmaVersion: 2015
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  eqeqeq:
    - error
    - always
  strict:
    - off
  max-len:
    - off
  one-var:
    - off
  padded-blocks:
    - off
  dot-location:
    - error
    - property